# Book settings
title: microdf documentation
author: Max Ghenis
logo: microdf_logo.png

launch_buttons:
  colab_url: "https://colab.research.google.com"

repository:
  url: https://github.com/MaxGhenis/microdf
  branch: master
  path_to_book: docs

html:
  use_edit_page_button  : true
  use_repository_button : true
  use_issues_button     : true

sphinx:
  extra_extensions          : ['sphinx.ext.autodoc', 'sphinx.ext.mathjax',
                               'sphinx.ext.viewcode', 'sphinx.ext.napoleon',
                               'alabaster']   # A list of extra extensions to load by Sphinx.
  config                    :   # key-value pairs to directly over-ride the Sphinx configuration